networks:
  network:
    external:
      name: network
#    name: network
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.35.1.0/24
services:
  modernParkingBot:
    container_name: modernParkingBot
    image: 1rznkv0/modern_parking_bot:latest
    restart: always
    networks:
      - network
    env_file:
      - .env

  psql:
    container_name: psql
    image: postgres:16.4
    restart: always
    networks:
      network:
        ipv4_address: 172.35.1.88
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "6432:5432"

volumes:
  pgdata:
